"""Where uploaded bytes actually live.

Everything above this module deals in *storage keys* - opaque strings like
``2026/09/3f9a....jpg``. Nothing else in the codebase knows whether those
resolve to a local directory or an object-store bucket, which is the whole
point: swapping :class:`LocalStorageService` for an S3 or GCS implementation
should touch this file and the config, and nothing else.

Filenames
---------

A stored filename is **always** ``<uuid4><ext>`` and never derives from what
the client sent. A client-supplied name can contain ``../`` to escape the
upload root, a null byte to truncate a path, a name that collides with an
existing file, or an extension the web server will happily execute. Generating
the name removes all four problems at once rather than trying to sanitise a
hostile string into safety. The original is kept in the database for display.

Keys are date-partitioned (``YYYY/MM/``) so a directory never grows to the
millions of entries that make local filesystem operations crawl.
"""
from __future__ import annotations

import os
import uuid
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from pathlib import Path
from typing import BinaryIO

from flask import current_app

# Chunk size for streaming a file to disk. Large enough to be efficient, small
# enough that a big upload never sits in memory in one piece.
COPY_CHUNK_BYTES = 64 * 1024


class StorageError(RuntimeError):
    """Raised when the storage backend cannot complete an operation."""


class BaseStorageService(ABC):
    """The contract every storage backend must satisfy."""

    @abstractmethod
    def save_file(self, file_obj: BinaryIO, filename: str) -> str:
        """Persist a stream and return its storage key.

        ``filename`` is the *original* client name, used only to pick a
        sensible extension. The returned key is what the caller stores.
        """

    @abstractmethod
    def delete_file(self, file_path: str) -> bool:
        """Remove a stored object. True if it was there, False if not."""

    @abstractmethod
    def get_file_path(self, file_path: str) -> str:
        """Resolve a storage key to something servable."""

    @abstractmethod
    def exists(self, file_path: str) -> bool:
        """Whether the object is actually present."""


def build_storage_key(original_filename: str, allowed_extensions: set[str]) -> str:
    """Generate ``YYYY/MM/<uuid4><ext>`` from an untrusted filename.

    Only the extension is taken from the client, and only if it is on the
    allowlist - so a name like ``../../etc/passwd`` or ``payload.php.jpg``
    contributes nothing but, at most, ``.jpg``.
    """
    suffix = Path(original_filename or "").suffix.lower()
    if suffix not in allowed_extensions:
        suffix = ""
    now = datetime.now(timezone.utc)
    return f"{now:%Y/%m}/{uuid.uuid4().hex}{suffix}"


class LocalStorageService(BaseStorageService):
    """Stores files on the local filesystem.

    The development and test backend. Not suitable for more than one process on
    more than one machine - that is what the abstraction is for.
    """

    def __init__(self, root: str | os.PathLike | None = None) -> None:
        self._root = Path(root) if root else None

    @property
    def root(self) -> Path:
        """The upload directory, created on first use.

        Read from config at access time rather than at construction, so a test
        can point the service at a temporary directory without rebuilding it.
        """
        root = self._root or Path(current_app.config["UPLOAD_FOLDER"])
        root.mkdir(parents=True, exist_ok=True)
        return root

    def _resolve(self, file_path: str) -> Path:
        """Turn a storage key into an absolute path, refusing to escape the root.

        Keys are generated by this module and should always be safe, but this
        is the last line before the filesystem: if a crafted key ever reaches
        here from a corrupted row or a future backend, it stops at this check
        rather than reading arbitrary files.
        """
        root = self.root.resolve()
        candidate = (root / file_path).resolve()
        try:
            candidate.relative_to(root)
        except ValueError:
            raise StorageError(f"Refusing to access a path outside storage: {file_path}")
        return candidate

    def save_file(self, file_obj: BinaryIO, filename: str) -> str:
        from .media_service import ALLOWED_EXTENSIONS

        key = build_storage_key(filename, ALLOWED_EXTENSIONS)
        destination = self._resolve(key)
        destination.parent.mkdir(parents=True, exist_ok=True)

        try:
            file_obj.seek(0)
        except (AttributeError, OSError):
            # Some streams are not seekable; write from wherever they are.
            pass

        try:
            with destination.open("wb") as handle:
                while True:
                    chunk = file_obj.read(COPY_CHUNK_BYTES)
                    if not chunk:
                        break
                    handle.write(chunk)
        except OSError as exc:
            # Never leave a half-written file behind to be served later.
            destination.unlink(missing_ok=True)
            raise StorageError(f"Could not store the file: {exc}") from None

        return key

    def delete_file(self, file_path: str) -> bool:
        try:
            target = self._resolve(file_path)
        except StorageError:
            return False
        try:
            target.unlink()
            return True
        except FileNotFoundError:
            # Already gone is the desired end state, not an error.
            return False
        except OSError as exc:
            raise StorageError(f"Could not delete the file: {exc}") from None

    def get_file_path(self, file_path: str) -> str:
        return str(self._resolve(file_path))

    def exists(self, file_path: str) -> bool:
        try:
            return self._resolve(file_path).is_file()
        except StorageError:
            return False


_STORAGE_KEY = "_betternepal_storage"


def get_storage() -> BaseStorageService:
    """The storage backend for this application.

    Cached on the app so every request shares one instance. Swapping in a cloud
    backend later means changing this function and nothing above it.
    """
    storage = current_app.extensions.get(_STORAGE_KEY)
    if storage is None:
        storage = LocalStorageService()
        current_app.extensions[_STORAGE_KEY] = storage
    return storage
