"""phase 11: incident resolved_at for analytics

Revision ID: 06e09d74f30b
Revises: e264382bce4f
Create Date: 2026-09-18 19:05:46.890491

"""
from alembic import op
import sqlalchemy as sa
# Custom column types (e.g. UtcDateTime) are rendered by Alembic as
# fully-qualified names, so the module must be importable here.
import app.models.base  # noqa: F401
import app.gis.types  # noqa: F401


# revision identifiers, used by Alembic.
revision = '06e09d74f30b'
down_revision = 'e264382bce4f'
branch_labels = None
depends_on = None


def upgrade():
    # Deliberately NOT backfilled. Incidents resolved before this column
    # existed have no true resolution time, and `updated_at` is not one - it
    # moves on any edit, so copying it would invent precise-looking timings
    # that are simply wrong. Those rows stay NULL and the analytics service
    # counts them as `unmeasured` against a stated denominator.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_at', app.models.base.UtcDateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_incidents_resolved_at'), ['resolved_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_resolved_at'))
        batch_op.drop_column('resolved_at')

    # ### end Alembic commands ###
