"""phase 9: media attachments

Revision ID: 3531362ea024
Revises: 5efd9e42eb95
Create Date: 2026-09-18 16:28:12.794552

"""
from alembic import op
import sqlalchemy as sa
# Custom column types (e.g. UtcDateTime) are rendered by Alembic as
# fully-qualified names, so the module must be importable here.
import app.models.base  # noqa: F401
import app.gis.types  # noqa: F401


# revision identifiers, used by Alembic.
revision = '3531362ea024'
down_revision = '5efd9e42eb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('report', 'incident', 'project', 'progress_update', name='media_entity_type', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'document', name='media_type', native_enum=False), nullable=False),
    sa.CheckConstraint('file_size_bytes > 0', name='ck_media_attachments_size_positive'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name='fk_media_attachments_uploader_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_attachments', schema=None) as batch_op:
        batch_op.create_index('ix_media_attachments_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_media_attachments_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_attachments_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_attachments_uploader_id'), ['uploader_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_attachments_uploader_id'))
        batch_op.drop_index(batch_op.f('ix_media_attachments_media_type'))
        batch_op.drop_index('ix_media_attachments_entity')
        batch_op.drop_index('ix_media_attachments_created_at')

    op.drop_table('media_attachments')
    # ### end Alembic commands ###
