"""phase 19: district highways, emergency contacts, corridors, risk profile

Revision ID: 4ed0fe3e19cc
Revises: a2b11b58de58
Create Date: 2026-09-20 07:25:57.707798

"""
from alembic import op
import sqlalchemy as sa
# Custom column types (e.g. UtcDateTime) are rendered by Alembic as
# fully-qualified names, so the module must be importable here.
import app.models.base  # noqa: F401
import app.gis.types  # noqa: F401


# revision identifiers, used by Alembic.
revision = '4ed0fe3e19cc'
down_revision = 'a2b11b58de58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_broadcasts',
    sa.Column('threat_assessment_id', sa.Uuid(), nullable=True),
    sa.Column('disaster_incident_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('municipality_id', sa.Uuid(), nullable=True),
    sa.Column('hazard_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('title_ne', sa.Text(), nullable=False),
    sa.Column('title_mai', sa.Text(), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=False),
    sa.Column('content_ne', sa.Text(), nullable=False),
    sa.Column('content_mai', sa.Text(), nullable=False),
    sa.Column('action_en', sa.Text(), nullable=False),
    sa.Column('action_ne', sa.Text(), nullable=False),
    sa.Column('action_mai', sa.Text(), nullable=False),
    sa.Column('platforms_targeted', sa.JSON(), nullable=False),
    sa.Column('authorization_state', sa.Enum('pending_review', 'auto_approved', 'authority_approved', 'rejected', 'cancelled', 'expired', name='social_broadcast_auth_state', native_enum=False), server_default='pending_review', nullable=False),
    sa.Column('authorized_by_id', sa.Uuid(), nullable=True),
    sa.Column('authorized_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('authorization_reason', sa.Text(), nullable=True),
    sa.Column('dispatch_status', sa.JSON(), nullable=False),
    sa.Column('dispatch_status_summary', sa.String(length=32), nullable=False),
    sa.Column('ai_classification_confidence', sa.Float(), nullable=True),
    sa.Column('threat_confidence', sa.Float(), nullable=True),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=True),
    sa.Column('external_post_ids', sa.JSON(), nullable=False),
    sa.Column('parent_broadcast_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('published_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['disaster_incident_id'], ['disaster_incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_broadcast_id'], ['social_broadcasts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['threat_assessment_id'], ['threat_assessments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_broadcasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_broadcasts_authorization_state'), ['authorization_state'], unique=False)
        batch_op.create_index('ix_social_broadcasts_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_broadcasts_disaster_incident_id'), ['disaster_incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_broadcasts_district_id'), ['district_id'], unique=False)
        batch_op.create_index('ix_social_broadcasts_district_status', ['district_id', 'authorization_state'], unique=False)
        batch_op.create_index('ix_social_broadcasts_hazard_severity', ['hazard_type', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_broadcasts_municipality_id'), ['municipality_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_broadcasts_parent_broadcast_id'), ['parent_broadcast_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_broadcasts_threat_assessment_id'), ['threat_assessment_id'], unique=False)

    op.create_table('threat_assessments',
    sa.Column('hazard_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('observing', 'possible', 'corroborated', 'warning', 'critical', 'dismissed', 'expired', 'resolved', name='threat_assessment_status', native_enum=False), server_default='observing', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', app.gis.types.GeometryColumn('POINT', srid=4326), nullable=True),
    sa.Column('affected_radius_km', sa.Float(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('municipality_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('threat_confidence', sa.Float(), nullable=False),
    sa.Column('ai_classification_confidence', sa.Float(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('independent_evidence_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('source_reliability', sa.Enum('verified_authority', 'verified_sensor', 'multi_source_corroborated', 'trusted_report', 'unverified_citizen_report', 'unknown', name='threat_assessment_reliability', native_enum=False), server_default='unknown', nullable=False),
    sa.Column('confidence_basis', sa.JSON(), nullable=True),
    sa.Column('expires_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('broadcast_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_threat_assessments_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_threat_assessments_longitude_range'),
    sa.CheckConstraint('threat_confidence >= 0 AND threat_confidence <= 1', name='ck_threat_assessments_confidence_range'),
    sa.ForeignKeyConstraint(['broadcast_id'], ['social_broadcasts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_assessments_broadcast_id'), ['broadcast_id'], unique=False)
        batch_op.create_index('ix_threat_assessments_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_assessments_district_id'), ['district_id'], unique=False)
        batch_op.create_index('ix_threat_assessments_district_status', ['district_id', 'status'], unique=False)
        batch_op.create_index('ix_threat_assessments_hazard_status', ['hazard_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_assessments_hazard_type'), ['hazard_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_assessments_municipality_id'), ['municipality_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_assessments_status'), ['status'], unique=False)

    op.create_table('broadcast_deliveries',
    sa.Column('broadcast_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'published', 'failed', 'retrying', 'disabled', name='broadcast_delivery_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('published_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['broadcast_id'], ['social_broadcasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broadcast_id', 'platform', name='uq_broadcast_deliveries_broadcast_platform')
    )
    with op.batch_alter_table('broadcast_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcast_deliveries_broadcast_id'), ['broadcast_id'], unique=False)
        batch_op.create_index('ix_broadcast_deliveries_idempotency', ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_broadcast_deliveries_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_broadcast_deliveries_platform'), ['platform'], unique=False)
        batch_op.create_index('ix_broadcast_deliveries_status', ['status'], unique=False)

    op.create_table('district_corridors',
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('last_verified_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.CheckConstraint("verification_status IN ('unverified', 'reference_only', 'official_source', 'field_verified')", name='ck_district_corridors_verification_status'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'name', name='uq_district_corridors_district_name')
    )
    with op.batch_alter_table('district_corridors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_district_corridors_district_id'), ['district_id'], unique=False)

    op.create_table('district_emergency_contacts',
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('last_verified_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.CheckConstraint("kind IN ('deoc', 'police', 'hospital')", name='ck_district_emergency_contacts_kind'),
    sa.CheckConstraint("verification_status IN ('unverified', 'reference_only', 'official_source', 'field_verified')", name='ck_district_emergency_contacts_verification_status'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'kind', name='uq_district_emergency_contacts_district_kind')
    )
    with op.batch_alter_table('district_emergency_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_district_emergency_contacts_district_id'), ['district_id'], unique=False)

    op.create_table('district_highways',
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('last_verified_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.CheckConstraint("verification_status IN ('unverified', 'reference_only', 'official_source', 'field_verified')", name='ck_district_highways_verification_status'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'code', name='uq_district_highways_district_code')
    )
    with op.batch_alter_table('district_highways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_district_highways_district_id'), ['district_id'], unique=False)

    op.create_table('district_risk_profiles',
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('hazard_type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('last_verified_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.CheckConstraint("verification_status IN ('unverified', 'reference_only', 'official_source', 'field_verified')", name='ck_district_risk_profiles_verification_status'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'hazard_type', name='uq_district_risk_profiles_district_hazard')
    )
    with op.batch_alter_table('district_risk_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_district_risk_profiles_district_id'), ['district_id'], unique=False)

    op.create_table('threat_signals',
    sa.Column('source_type', sa.Enum('citizen_report', 'authority_report', 'sensor', 'weather_signal', 'incident_cluster', 'road_status', 'flood_signal', 'landslide_signal', 'earthquake_signal', 'fire_signal', 'system_signal', name='threat_signal_source_type', native_enum=False), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('received_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('occurred_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', app.gis.types.GeometryColumn('POINT', srid=4326), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('municipality_id', sa.Uuid(), nullable=True),
    sa.Column('hazard_type', sa.String(length=64), nullable=True),
    sa.Column('severity_hint', sa.String(length=32), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('structured_payload', sa.JSON(), nullable=True),
    sa.Column('source_reliability', sa.Enum('verified_authority', 'verified_sensor', 'multi_source_corroborated', 'trusted_report', 'unverified_citizen_report', 'unknown', name='threat_signal_reliability', native_enum=False), server_default='unknown', nullable=False),
    sa.Column('verification_status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('threat_assessment_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_threat_signals_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_threat_signals_longitude_range'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['threat_assessment_id'], ['threat_assessments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_signals', schema=None) as batch_op:
        batch_op.create_index('ix_threat_signals_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_signals_district_id'), ['district_id'], unique=False)
        batch_op.create_index('ix_threat_signals_district_source', ['district_id', 'source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_signals_hazard_type'), ['hazard_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_signals_municipality_id'), ['municipality_id'], unique=False)
        batch_op.create_index('ix_threat_signals_received_at', ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_signals_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_signals_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_signals_threat_assessment_id'), ['threat_assessment_id'], unique=False)

    with op.batch_alter_table('disaster_incidents', schema=None) as batch_op:
        batch_op.alter_column('disaster_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('earthquake', 'flood', 'flash_flood', 'landslide', 'forest_fire', 'storm', 'lightning', 'avalanche', 'wildfire', 'other', 'none', name='disaster_incident_type', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('low', 'moderate', 'high', 'critical', name='disaster_incident_severity', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'moderate'"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('detected', 'triaged', 'dispatched', 'acknowledged', 'responding', 'resolved', 'false_alarm', name='disaster_incident_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'detected'"))
        batch_op.create_index(batch_op.f('ix_disaster_incidents_assigned_by_id'), ['assigned_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_incidents_authority_id'), ['authority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_incidents_disaster_type'), ['disaster_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_incidents_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_incidents_municipality_id'), ['municipality_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_incidents_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_incidents_source_report_id'), ['source_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_incidents_status'), ['status'], unique=False)

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_mai', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('headquarters', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('headquarters')
        batch_op.drop_column('name_mai')

    with op.batch_alter_table('disaster_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disaster_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_disaster_incidents_source_report_id'))
        batch_op.drop_index(batch_op.f('ix_disaster_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_disaster_incidents_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_disaster_incidents_municipality_id'))
        batch_op.drop_index(batch_op.f('ix_disaster_incidents_district_id'))
        batch_op.drop_index(batch_op.f('ix_disaster_incidents_disaster_type'))
        batch_op.drop_index(batch_op.f('ix_disaster_incidents_authority_id'))
        batch_op.drop_index(batch_op.f('ix_disaster_incidents_assigned_by_id'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('detected', 'triaged', 'dispatched', 'acknowledged', 'responding', 'resolved', 'false_alarm', name='disaster_incident_status', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'detected'"))
        batch_op.alter_column('severity',
               existing_type=sa.Enum('low', 'moderate', 'high', 'critical', name='disaster_incident_severity', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'moderate'"))
        batch_op.alter_column('disaster_type',
               existing_type=sa.Enum('earthquake', 'flood', 'flash_flood', 'landslide', 'forest_fire', 'storm', 'lightning', 'avalanche', 'wildfire', 'other', 'none', name='disaster_incident_type', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('threat_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_signals_threat_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_threat_signals_source_type'))
        batch_op.drop_index(batch_op.f('ix_threat_signals_source_id'))
        batch_op.drop_index('ix_threat_signals_received_at')
        batch_op.drop_index(batch_op.f('ix_threat_signals_municipality_id'))
        batch_op.drop_index(batch_op.f('ix_threat_signals_hazard_type'))
        batch_op.drop_index('ix_threat_signals_district_source')
        batch_op.drop_index(batch_op.f('ix_threat_signals_district_id'))
        batch_op.drop_index('ix_threat_signals_created_at')

    op.drop_table('threat_signals')
    with op.batch_alter_table('district_risk_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_district_risk_profiles_district_id'))

    op.drop_table('district_risk_profiles')
    with op.batch_alter_table('district_highways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_district_highways_district_id'))

    op.drop_table('district_highways')
    with op.batch_alter_table('district_emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_district_emergency_contacts_district_id'))

    op.drop_table('district_emergency_contacts')
    with op.batch_alter_table('district_corridors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_district_corridors_district_id'))

    op.drop_table('district_corridors')
    with op.batch_alter_table('broadcast_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_broadcast_deliveries_status')
        batch_op.drop_index(batch_op.f('ix_broadcast_deliveries_platform'))
        batch_op.drop_index(batch_op.f('ix_broadcast_deliveries_idempotency_key'))
        batch_op.drop_index('ix_broadcast_deliveries_idempotency')
        batch_op.drop_index(batch_op.f('ix_broadcast_deliveries_broadcast_id'))

    op.drop_table('broadcast_deliveries')
    with op.batch_alter_table('threat_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_assessments_status'))
        batch_op.drop_index(batch_op.f('ix_threat_assessments_municipality_id'))
        batch_op.drop_index(batch_op.f('ix_threat_assessments_hazard_type'))
        batch_op.drop_index('ix_threat_assessments_hazard_status')
        batch_op.drop_index('ix_threat_assessments_district_status')
        batch_op.drop_index(batch_op.f('ix_threat_assessments_district_id'))
        batch_op.drop_index('ix_threat_assessments_created_at')
        batch_op.drop_index(batch_op.f('ix_threat_assessments_broadcast_id'))

    op.drop_table('threat_assessments')
    with op.batch_alter_table('social_broadcasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_broadcasts_threat_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_social_broadcasts_parent_broadcast_id'))
        batch_op.drop_index(batch_op.f('ix_social_broadcasts_municipality_id'))
        batch_op.drop_index('ix_social_broadcasts_hazard_severity')
        batch_op.drop_index('ix_social_broadcasts_district_status')
        batch_op.drop_index(batch_op.f('ix_social_broadcasts_district_id'))
        batch_op.drop_index(batch_op.f('ix_social_broadcasts_disaster_incident_id'))
        batch_op.drop_index('ix_social_broadcasts_created_at')
        batch_op.drop_index(batch_op.f('ix_social_broadcasts_authorization_state'))

    op.drop_table('social_broadcasts')
    # ### end Alembic commands ###
