"""phase 7: authorities and incident routing

Revision ID: 571ff9382a0b
Revises: f5392ef829e1
Create Date: 2026-09-18 16:02:32.922506

"""
from alembic import op
import sqlalchemy as sa
# Custom column types (e.g. UtcDateTime) are rendered by Alembic as
# fully-qualified names, so the module must be importable here.
import app.models.base  # noqa: F401
import app.gis.types  # noqa: F401


# revision identifiers, used by Alembic.
revision = '571ff9382a0b'
down_revision = 'f5392ef829e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorities',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level', sa.Enum('federal', 'provincial', 'local', 'utility', name='authority_level', native_enum=False), nullable=False),
    sa.Column('type', sa.Enum('department_of_roads', 'municipal_office', 'water_authority', 'electricity_authority', 'other', name='authority_type', native_enum=False), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name='fk_authorities_district_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authorities_district_id'), ['district_id'], unique=False)
        batch_op.create_index('ix_authorities_district_level', ['district_id', 'level'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorities_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorities_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_authorities_type'), ['type'], unique=False)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authority_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('assigned_by_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('assigned_at', app.models.base.UtcDateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_incidents_assigned_by_id'), ['assigned_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_authority_id'), ['authority_id'], unique=False)
        batch_op.create_foreign_key('fk_incidents_authority_id', 'authorities', ['authority_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_incidents_assigned_by_id', 'users', ['assigned_by_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incidents_assigned_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_incidents_authority_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_incidents_authority_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_assigned_by_id'))
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('assigned_by_id')
        batch_op.drop_column('authority_id')

    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authorities_type'))
        batch_op.drop_index(batch_op.f('ix_authorities_name'))
        batch_op.drop_index(batch_op.f('ix_authorities_level'))
        batch_op.drop_index('ix_authorities_district_level')
        batch_op.drop_index(batch_op.f('ix_authorities_district_id'))

    op.drop_table('authorities')
    # ### end Alembic commands ###
