"""phase 8: projects and progress ledger

Revision ID: 5efd9e42eb95
Revises: 571ff9382a0b
Create Date: 2026-09-18 16:17:21.383300

"""
from alembic import op
import sqlalchemy as sa
# Custom column types (e.g. UtcDateTime) are rendered by Alembic as
# fully-qualified names, so the module must be importable here.
import app.models.base  # noqa: F401
import app.gis.types  # noqa: F401


# revision identifiers, used by Alembic.
revision = '5efd9e42eb95'
down_revision = '571ff9382a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'on_hold', 'completed', 'cancelled', name='project_status', native_enum=False), server_default='planned', nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('authority_id', sa.Uuid(), nullable=False),
    sa.Column('contractor_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('estimated_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('start_date IS NULL OR actual_end_date IS NULL OR actual_end_date >= start_date', name='ck_projects_actual_end_after_start'),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], name='fk_projects_authority_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contractor_id'], ['users.id'], name='fk_projects_contractor_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_projects_incident_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_authority_id'), ['authority_id'], unique=False)
        batch_op.create_index('ix_projects_authority_status', ['authority_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_contractor_id'), ['contractor_id'], unique=False)
        batch_op.create_index('ix_projects_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('progress_updates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('previous_status', sa.Enum('planned', 'active', 'on_hold', 'completed', 'cancelled', name='progress_previous_status', native_enum=False), nullable=True),
    sa.Column('new_status', sa.Enum('planned', 'active', 'on_hold', 'completed', 'cancelled', name='progress_new_status', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_progress_updates_author_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_progress_updates_project_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_updates_author_id'), ['author_id'], unique=False)
        batch_op.create_index('ix_progress_updates_project_created', ['project_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_updates_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_updates_project_id'))
        batch_op.drop_index('ix_progress_updates_project_created')
        batch_op.drop_index(batch_op.f('ix_progress_updates_author_id'))

    op.drop_table('progress_updates')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_incident_id'))
        batch_op.drop_index('ix_projects_created_at')
        batch_op.drop_index(batch_op.f('ix_projects_contractor_id'))
        batch_op.drop_index('ix_projects_authority_status')
        batch_op.drop_index(batch_op.f('ix_projects_authority_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###
