"""phase 4: districts and municipalities

Revision ID: 88630c7d1e60
Revises: 43d64c4a9d0b
Create Date: 2026-09-18 15:13:26.438579

"""
from alembic import op
import sqlalchemy as sa
# Custom column types (e.g. UtcDateTime) are rendered by Alembic as
# fully-qualified names, so the module must be importable here.
import app.models.base  # noqa: F401
import app.gis.types  # noqa: F401


# revision identifiers, used by Alembic.
revision = '88630c7d1e60'
down_revision = '43d64c4a9d0b'
branch_labels = None
depends_on = None


def upgrade():
    # PostGIS supplies the `geometry` type used by the boundary columns below,
    # so the extension must exist before either table is created. Autogenerate
    # cannot know this, so it is added by hand. Harmless if a DBA has already
    # installed it; on a non-PostgreSQL database there is nothing to do.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ne', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('boundary', app.gis.types.GeometryColumn('MULTIPOLYGON', srid=4326), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('last_verified_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.CheckConstraint("verification_status IN ('unverified', 'reference_only', 'official_source', 'field_verified')", name='ck_districts_verification_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_districts_name')
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_index('ix_districts_boundary', ['boundary'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_districts_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_districts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_districts_province'), ['province'], unique=False)

    op.create_table('municipalities',
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ne', sa.String(length=120), nullable=True),
    sa.Column('municipality_type', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('boundary', app.gis.types.GeometryColumn('MULTIPOLYGON', srid=4326), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('last_verified_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.CheckConstraint("municipality_type IS NULL OR municipality_type IN ('metropolitan', 'sub_metropolitan', 'municipality', 'rural_municipality')", name='ck_municipalities_type'),
    sa.CheckConstraint("verification_status IN ('unverified', 'reference_only', 'official_source', 'field_verified')", name='ck_municipalities_verification_status'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'name', name='uq_municipalities_district_name')
    )
    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        batch_op.create_index('ix_municipalities_boundary', ['boundary'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_municipalities_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_municipalities_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_municipalities_municipality_type'), ['municipality_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_municipalities_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipalities_name'))
        batch_op.drop_index(batch_op.f('ix_municipalities_municipality_type'))
        batch_op.drop_index(batch_op.f('ix_municipalities_district_id'))
        batch_op.drop_index(batch_op.f('ix_municipalities_code'))
        batch_op.drop_index('ix_municipalities_boundary', postgresql_using='gist')

    op.drop_table('municipalities')
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_districts_province'))
        batch_op.drop_index(batch_op.f('ix_districts_name'))
        batch_op.drop_index(batch_op.f('ix_districts_code'))
        batch_op.drop_index('ix_districts_boundary', postgresql_using='gist')

    op.drop_table('districts')
    # ### end Alembic commands ###
    # The postgis extension is intentionally left installed: dropping it would
    # cascade into any other schema using geometry, and it is cheap to keep.
