"""users: permanent and temporary district

Revision ID: 95dc4329bd09
Revises: de442c6b39ff
Create Date: 2026-09-19 01:28:43.490671

"""
from alembic import op
import sqlalchemy as sa
# Custom column types (e.g. UtcDateTime) are rendered by Alembic as
# fully-qualified names, so the module must be importable here.
import app.models.base  # noqa: F401
import app.gis.types  # noqa: F401


# revision identifiers, used by Alembic.
revision = '95dc4329bd09'
down_revision = 'de442c6b39ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permanent_district_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('temporary_district_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_permanent_district_id'), ['permanent_district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_temporary_district_id'), ['temporary_district_id'], unique=False)
        batch_op.create_foreign_key('fk_users_temporary_district_id', 'districts', ['temporary_district_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_users_permanent_district_id', 'districts', ['permanent_district_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_permanent_district_id', type_='foreignkey')
        batch_op.drop_constraint('fk_users_temporary_district_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_temporary_district_id'))
        batch_op.drop_index(batch_op.f('ix_users_permanent_district_id'))
        batch_op.drop_column('temporary_district_id')
        batch_op.drop_column('permanent_district_id')

    # ### end Alembic commands ###
