"""phase 5: citizen reports

Revision ID: bd17f6518ed2
Revises: 88630c7d1e60
Create Date: 2026-09-18 15:39:36.993902

"""
from alembic import op
import sqlalchemy as sa
# Custom column types (e.g. UtcDateTime) are rendered by Alembic as
# fully-qualified names, so the module must be importable here.
import app.models.base  # noqa: F401
import app.gis.types  # noqa: F401


# revision identifiers, used by Alembic.
revision = 'bd17f6518ed2'
down_revision = '88630c7d1e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('road_damage', 'water_leak', 'waste_management', 'electricity', 'public_property', 'natural_disaster', 'other', name='report_category', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'verified_as_incident', 'rejected', name='report_status', native_enum=False), server_default='submitted', nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('municipality_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', app.gis.types.GeometryColumn('POINT', srid=4326), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_reports_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_reports_longitude_range'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_category'), ['category'], unique=False)
        batch_op.create_index('ix_reports_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_district_id'), ['district_id'], unique=False)
        batch_op.create_index('ix_reports_district_status', ['district_id', 'status'], unique=False)
        batch_op.create_index('ix_reports_location', ['location'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_reports_municipality_id'), ['municipality_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_reports_municipality_id'))
        batch_op.drop_index('ix_reports_location', postgresql_using='gist')
        batch_op.drop_index('ix_reports_district_status')
        batch_op.drop_index(batch_op.f('ix_reports_district_id'))
        batch_op.drop_index('ix_reports_created_at')
        batch_op.drop_index(batch_op.f('ix_reports_category'))

    op.drop_table('reports')
    # ### end Alembic commands ###
