"""announcements: social feed and disaster alert drafts

Revision ID: de442c6b39ff
Revises: 06e09d74f30b
Create Date: 2026-09-19 00:40:24.230416

"""
from alembic import op
import sqlalchemy as sa
# Custom column types (e.g. UtcDateTime) are rendered by Alembic as
# fully-qualified names, so the module must be importable here.
import app.models.base  # noqa: F401
import app.gis.types  # noqa: F401


# revision identifiers, used by Alembic.
revision = 'de442c6b39ff'
down_revision = '06e09d74f30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_announcements_author_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name='fk_announcements_district_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_district_id'), ['district_id'], unique=False)
        batch_op.create_index('ix_announcements_feed', ['district_id', 'is_draft', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_is_draft'), ['is_draft'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_is_draft'))
        batch_op.drop_index('ix_announcements_feed')
        batch_op.drop_index(batch_op.f('ix_announcements_district_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_author_id'))

    op.drop_table('announcements')
    # ### end Alembic commands ###
