"""phase 10: ai metadata and duplicate links

Revision ID: e264382bce4f
Revises: 3531362ea024
Create Date: 2026-09-18 16:48:06.229043

"""
from alembic import op
import sqlalchemy as sa
# Custom column types (e.g. UtcDateTime) are rendered by Alembic as
# fully-qualified names, so the module must be importable here.
import app.models.base  # noqa: F401
import app.gis.types  # noqa: F401


# revision identifiers, used by Alembic.
revision = 'e264382bce4f'
down_revision = '3531362ea024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('duplicate_of_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reports_duplicate_of_id'), ['duplicate_of_id'], unique=False)
        batch_op.create_foreign_key('fk_reports_duplicate_of_id', 'reports', ['duplicate_of_id'], ['id'], ondelete='SET NULL')
        # Added by hand: Alembic's autogenerate does not compare CHECK
        # constraints on an existing table, so without this the model would
        # enforce it under create_all (the test suite) while a migrated
        # database would not - a silent divergence between test and production.
        # A self-referencing duplicate would make the chain a cycle.
        batch_op.create_check_constraint(
            'ck_reports_not_self_duplicate',
            'duplicate_of_id IS NULL OR duplicate_of_id <> id',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('ck_reports_not_self_duplicate', type_='check')
        batch_op.drop_constraint('fk_reports_duplicate_of_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_duplicate_of_id'))
        batch_op.drop_column('duplicate_of_id')
        batch_op.drop_column('ai_metadata')

    # ### end Alembic commands ###
