"""phase 6: incidents and report clustering

Revision ID: f5392ef829e1
Revises: bd17f6518ed2
Create Date: 2026-09-18 15:51:44.479588

"""
from alembic import op
import sqlalchemy as sa
# Custom column types (e.g. UtcDateTime) are rendered by Alembic as
# fully-qualified names, so the module must be importable here.
import app.models.base  # noqa: F401
import app.gis.types  # noqa: F401


# revision identifiers, used by Alembic.
revision = 'f5392ef829e1'
down_revision = 'bd17f6518ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('road_damage', 'water_leak', 'waste_management', 'electricity', 'public_property', 'natural_disaster', 'other', name='incident_category', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incident_severity', native_enum=False), server_default='medium', nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='incident_status', native_enum=False), server_default='open', nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('municipality_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', app.gis.types.GeometryColumn('POINT', srid=4326), nullable=True),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_incidents_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_incidents_longitude_range'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_category'), ['category'], unique=False)
        batch_op.create_index('ix_incidents_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_district_id'), ['district_id'], unique=False)
        batch_op.create_index('ix_incidents_district_status', ['district_id', 'status'], unique=False)
        batch_op.create_index('ix_incidents_location', ['location'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_incidents_municipality_id'), ['municipality_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_verified_by_id'), ['verified_by_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incident_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reports_incident_id'), ['incident_id'], unique=False)
        batch_op.create_foreign_key('fk_reports_incident_id', 'incidents', ['incident_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reports_incident_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_incident_id'))
        batch_op.drop_column('incident_id')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_verified_by_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_municipality_id'))
        batch_op.drop_index('ix_incidents_location', postgresql_using='gist')
        batch_op.drop_index('ix_incidents_district_status')
        batch_op.drop_index(batch_op.f('ix_incidents_district_id'))
        batch_op.drop_index('ix_incidents_created_at')
        batch_op.drop_index(batch_op.f('ix_incidents_category'))

    op.drop_table('incidents')
    # ### end Alembic commands ###
